### ISSUE TITLE
flutter_map dependency update

### ISSUE THREAD

**Issue by talamaska** [Michael-M-aher/location_picker_flutter_map#13]
I'm currently blocked of using flutter_map 4 because of location_picker_flutter_map dependency conflict. Is it possible to update it?

**Comment by harshhhh15** [comment]
You have a few alternatives when dealing with dependency issues.:

1 Examine for package updates: First, check to see whether any updated versions of the packages you're using have resolved the conflict. For the most recent version information, see the package's official website, GitHub repository, or the pub.dev website.

2 If the conflict remains and there is no new version available, you can try utilising dependency overrides in your pubspec.yaml file. This allows you to specify a specific package's version or Git repository. However, use overrides with caution as they may bring other flaws or compatibility issues.

3 Contact the package maintainers: If you are unable to resolve the dispute on your own, consider contacting the package maintainers. They might be aware of the problem and working on a solution, or they might be able to offer advice on how to resolve it.

It should be noted that dependence conflicts can be complex and require careful thought. Furthermore, changing packages or employing dependency overrides may cause compatibility or stability concerns. As a result, after making any modifications, it is critical to properly test your application.

For the most up-to-date information on resolving the problem you are experiencing, I recommend visiting the official GitHub repository or contacting the maintainers of the flutter_map and location_picker_flutter_map packages.

**Comment by Michael-M-aher** [comment]
updated 👍

**Comment by talamaska** [comment]
@Michael-M-aher Hi, thanks for the update. Btw, flutter_map is already on v6, seems quite a big list of changes.
[flutter_map](https://pub.dev/packages/flutter_map/changelog)

**Comment by dhafinrayhan** [comment]
@talamaska I've opened a pull request for that update: https://github.com/Michael-M-aher/location_picker_flutter_map/pull/27
