### ISSUE TITLE
Address as a map vs. address as an object

### ISSUE THREAD

**Issue by MahMoos** [Michael-M-aher/location_picker_flutter_map#2]
The latest release introduces a problem with serializing addresses from the response of osm. As you may know, the address object may be different from one location to another, from one country to another. This is the data object for a location inside Italy: 
`{
    hamlet: Pereto, 
    village: Monte Cerignone, 
    county: Pesaro e Urbino, 
    ISO3166-2-lvl6: IT-PU, 
    state: Marche, 
    ISO3166-2-lvl4: IT-57, 
    postcode: 61023, 
    country: Italia, 
    country_code: it
}`
And this is the data object for a location inside Ireland:
`{
  road: Clones Road,
  city_district: Drumcarn ED,
  region: Bailieborough-Cootehill Municipal District,
  county: County Cavan,
  ISO3166-2-lvl6: IE-CN,
  postcode: H12 E392,
  country: Éire / Ireland,
  country_code: ie
}`
As you can see they are not the same. And the properties serialized in the Address class will not cover all the info of an address. I suggest reverting it back to a map.

**Comment by Michael-M-aher** [comment]
done

**Comment by MahMoos** [comment]
Thanks
