### ISSUE TITLE
fix location support while looking around

### ISSUE THREAD

**Issue by thunderbug1** [Michael-M-aher/location_picker_flutter_map#28]
Thank you for the great package :)
I can't figure out how to change the behavior of the location marker. By default it is always centered on the screen but if you want to check out where this is and scroll around to see the surroundings then you also change the location which is not really what I want.
Is there a way to keep the marker where it is and only update it when the user taps on a point on the map? Similar to how google maps handles it when you click on a location.

**Comment by Michael-M-aher** [comment]
Thanks for your interest.
I will try to work on it.
