### ISSUE TITLE
flutter_map_cancellable_tile_provider recommendation despite it being installed

### ISSUE THREAD

**Issue by thunderbug1** [Michael-M-aher/location_picker_flutter_map#29]
I recently upgraded to version 1.0.0 and since then I see these messages in the debug console:

flutter_map
js_primitives.dart:30 │ 💡 Consider installing the official 'flutter_map_cancellable_tile_provider' plugin for improved
js_primitives.dart:30 │ 💡 performance on the web.
js_primitives.dart:30 │ 💡 See https://pub.dev/packages/flutter_map_cancellable_tile_provider for more info.

So I installed the package and rebuilt the app but I still get the recommendation.

**Comment by thunderbug1** [comment]
I do see canceled map png requests, so I guess the package is used anyway:
![image](https://github.com/Michael-M-aher/location_picker_flutter_map/assets/1395321/f9418f43-cf8e-407d-bb79-2f9da45e087d)

**Comment by Michael-M-aher** [comment]
added in version 2.1.0 ✅
