### ISSUE TITLE
Vector map support

### ISSUE THREAD

**Issue by thunderbug1** [Michael-M-aher/location_picker_flutter_map#31]
Is it possible to add vector map support? There is an extension for flutter_map that should make it easy: [flutter-vector-map-tiles](https://github.com/greensopinion/flutter-vector-map-tiles)

I could help with this as well.

**Comment by Michael-M-aher** [comment]
vector_map_tiles  depends on flutter_map 5 but my package depends on flutter_map 6 so it their is dependency error
