### ISSUE TITLE
Encountering an issue after entering an address and selecting it from the search results.

### ISSUE THREAD

**Issue by cclavijo** [Michael-M-aher/location_picker_flutter_map#34]
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
#0      _FlutterLocationPickerState.onLocationChanged.<anonymous closure> (package:location_picker_flutter_map/src/location_picker.dart:413:25)
<asynchronous suspension>
**Another exception was thrown: Exception: Buffer parameter must not be null**

**Comment by Michael-M-aher** [comment]
Fixed ✅
