### ISSUE TITLE
Restrict selectable location to specified area

### ISSUE THREAD

**Issue by giaur500** [Michael-M-aher/location_picker_flutter_map#37]
I need to restrict location allowed to be selected to specified area. So I need to:
- draw my city border on map (geojson polygon)
- throw message when selected location is outside city border

Is there any way to do that, or that functionality needs to be added? As I can see, there's some callback methods called on position change, so they could be used to check if current position is inside city border and possibly block selecting location outside the city, can I also draw anything I need on map (city border in this case).

**Comment by Michael-M-aher** [comment]
now on version 3.1.0 you can find mapLayers attribute and you can add polygon layer or any layer you want to throw meassage you can use any service you want and validate the picked location in the onPicked or onChanged

**Comment by giaur500** [comment]
> you can use any service you want and validate the picked location in the onPicked or onChanged

I know which polygon should be validated, I know its coordinates. I don't know what do you mean by "any service" - I still need to calculate if picked location is inside polygon or not. As I understand, you mean version 3.1.0 introduces easier way to access polygon, right? Or, your lib is able to check it automatically and throw exception? Please clarify - I am able to draw polygon, but I still need to validate location by myself?

For that purpose, I forked your lib and I just added polygon draw feature + validation location is inside polygon or not.

**Comment by Michael-M-aher** [comment]
To validate location you need to impliment point-in-polygon algorithm
