### ISSUE TITLE
Initial map position before initPosition attribute

### ISSUE THREAD

**Issue by Bylinkk** [Michael-M-aher/location_picker_flutter_map#39]
Hi, thanks for your work.
When the map opens, the displayed position is in Egypt before the initPosition attribute is applied. Can we change the starting position of the map? Thank you in advance for your feedback

**Comment by CoocooFroggy** [comment]
@Bylinkk feel free to try #45 and let me know if that solves the issue!

**Comment by Michael-M-aher** [comment]
Fixed in version 3.1.0 ✅
