### ISSUE TITLE
Bug: Searchbar sometimes changes after result

### ISSUE THREAD

**Issue by frieder-audriga** [Michael-M-aher/location_picker_flutter_map#42]
Using version 3.0.1 of this library, tapping a search result in the search bar can sometimes result in a different result being displayed:

Example:
* Type "Backwerk" in the search bar.
* Choose the first result: "Backwerk 11, Hardenbergplatz, Charlottenburg, Charlottenburg-Wilmersdorf, Berlin, 10623, Germany"

Expected Behavior:
* Animation of Map to that Location
* Search bar reads "Backwerk 11, Hardenbergplatz, Charlottenburg, Charlottenburg-Wilmersdorf, Berlin, 10623, Germany"

Observed Behaviour:
* Animation of Map to that Location
* Search bar reads "Zoologischer Garten, Hardenbergstraße, C..."

This happens with different stores that are located in train stations or shopping centers too.

I think the root cause is that tapping the result will
* Geocode the result into coordinates and  trigger the map to move to that location
* This triggers `onLocationChanged`, which then reverse-geocodes the coordinates back into an address (which can differ from the initial result because of inaccuracies).

So maybe if the result of the search that has been tapped can be re-used in onLocationChanged, this issue could be avoided.

**Comment by Michael-M-aher** [comment]
fixed on version 3.1.0 ✅
