### ISSUE TITLE
Button customization - width

### ISSUE THREAD

**Issue by giorgio79** [Michael-M-aher/location_picker_flutter_map#5]
Hello,

I would like to display a narrow button similar to  Scaffold floatingActionButton https://api.flutter.dev/flutter/material/FloatingActionButton-class.html

 instead of the current wide Elevated button https://github.com/Michael-M-aher/location_picker_flutter_map/blob/main/lib/src/Widgets/wide_button.dart 

Could we get perhaps the width configured to make it smaller? The rest of the style seems to be customizable via the ButtonStyle.

**Comment by Michael-M-aher** [comment]
I added customizations for the button position, width and height.
sorry for being late 😊.

**Comment by Michael-M-aher** [comment]
I added customizations for the button position, width and height.
sorry for being late 😊.
