### ISSUE TITLE
Old version Intl dependency

### ISSUE THREAD

**Issue by ZdenekKrcal** [Michael-M-aher/location_picker_flutter_map#8]
Please upgrade Intl dependency to 0.18.0 It is not possible to upgrade other packages because this package needs Intl version 0.17.0

**Comment by MahMoos** [comment]
You can add a dependency override to solve this by adding this to your `pubspec.yaml`:
```
dependency_overrides:
   intl: ^0.18.0
```

**Comment by ZdenekKrcal** [comment]
Yes thank you for the advice. But why can't be upgraded Intl in this package?

**Comment by MahMoos** [comment]
It might present conflicts with other popular packages that still use intl 0.17.0 such as firebase_ui_auth
